import { Box, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import MUI from "../images/MUI.png";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant="h1">DevALMO, YouTube channel</Typography>

        <Box sx={{ display: "block", maxWidth: "600px", width: "100%" }}>
          <Image src={MUI} alt="MUI" layout="responsive" />
        </Box>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
